meta_product_name: "John Marsden"
meta_title: "John Marsden - Full Stack Developer"
meta_description: "John Marsden - a full stack developer based in London, view projects for examples of his work"
meta_image: "cover.png" # should exist in `app/assets/images/`
