meta_product_name: "John Marsden"
meta_title: "John Marsden - Full Stack Developer"
meta_description: "Hi, I’m John, a UK based full stack developer living and working in London."
meta_image: "cover.png" # should exist in `app/assets/images/`
